run:
  test: 'echo meow > artifact.txt'
  test2: 'echo woof > artifact2.txt'
plugins:
  - artifacts: 'artifact*.txt'
  - publish: 'app'
docker-compose-file: foo
docker-registry: docker.groupondev.com
